export const data = [
  {
    categories: [
      {
        id: "b177647a-3231-4467-9641-7720ba4760ad",
        slug: "grocery-and-kitchen",
        name: "Grocery & Kitchen",
        subCategories: [
          {
            id: "553d3c7e-d5aa-48cb-be22-3273dbfb955f",
            slug: "fresh-vegetables",
            name: "Fresh Vegetables",
            products: [
              {
                id: "b34b55c7-77d8-454c-8571-1218bd30b8ad",
                name: "Carrots",
                quantity: "1kg",
                price: 80,
                description: "Fresh carrots, perfect for salads.",
                ingredients: "Carrots",
                nutritionalInfo: "Rich in beta carotene.",
                organic: true,
                slug: "carrots",
                image: "https://example.com/carrots.jpg",
              },
              {
                id: "bd1f327c-551e-4509-ba73-9ccccc99c6fd",
                name: "Tomatoes",
                quantity: "1kg",
                price: 60,
                description: "Juicy red tomatoes, great for cooking.",
                ingredients: "Tomatoes",
                nutritionalInfo: "High in lycopene.",
                organic: false,
                slug: "tomatoes",
                image: "https://example.com/tomatoes.jpg",
              },
              {
                id: "cb205319-33dd-46d0-8b3d-f4786fc396f4",
                name: "Potatoes",
                quantity: "1kg",
                price: 50,
                description: "Fresh potatoes, versatile for cooking.",
                ingredients: "Potatoes",
                nutritionalInfo: "Rich in carbohydrates.",
                organic: true,
                slug: "potatoes",
                image: "https://example.com/potatoes.jpg",
              },
              {
                id: "f8a523c8-f669-4867-8bbd-05bbe6eb0a02",
                name: "Spinach",
                quantity: "500g",
                price: 40,
                description: "Fresh spinach leaves, perfect for salads.",
                ingredients: "Spinach",
                nutritionalInfo: "High in iron.",
                organic: true,
                slug: "spinach",
                image: "https://example.com/spinach.jpg",
              },
              {
                id: "170748fb-553d-45c7-b390-5b8657c67479",
                name: "Broccoli",
                quantity: "500g",
                price: 100,
                description: "Fresh broccoli, packed with nutrients.",
                ingredients: "Broccoli",
                nutritionalInfo: "High in fiber.",
                organic: false,
                slug: "broccoli",
                image: "https://example.com/broccoli.jpg",
              },
              {
                id: "39aad8b5-880b-403f-ac89-7241373e3e39",
                name: "Bell Peppers",
                quantity: "500g",
                price: 90,
                description: "Colorful bell peppers for your meals.",
                ingredients: "Bell Peppers",
                nutritionalInfo: "Rich in vitamins A and C.",
                organic: true,
                slug: "bell-peppers",
                image: "https://example.com/bell-peppers.jpg",
              },
              {
                id: "e2d71f67-e11b-4f4b-ba03-b29f73f788eb",
                name: "Onions",
                quantity: "1kg",
                price: 40,
                description: "Fresh onions, essential for cooking.",
                ingredients: "Onions",
                nutritionalInfo: "Contains antioxidants.",
                organic: false,
                slug: "onions",
                image: "https://example.com/onions.jpg",
              },
              {
                id: "a65cdf9b-bb8d-45f6-85e9-d5471197e7d3",
                name: "Cabbage",
                quantity: "1kg",
                price: 30,
                description: "Fresh cabbage, great for salads.",
                ingredients: "Cabbage",
                nutritionalInfo: "Rich in fiber.",
                organic: true,
                slug: "cabbage",
                image: "https://example.com/cabbage.jpg",
              },
              {
                id: "e911717c-b9aa-4077-aadb-7422afcc4946",
                name: "Cucumbers",
                quantity: "500g",
                price: 40,
                description: "Fresh cucumbers, hydrating and crunchy.",
                ingredients: "Cucumbers",
                nutritionalInfo: "High in water content.",
                organic: false,
                slug: "cucumbers",
                image: "https://example.com/cucumbers.jpg",
              },
              {
                id: "4fa4a532-befe-49ec-8917-3f76d81ea3f2",
                name: "Lettuce",
                quantity: "500g",
                price: 30,
                description: "Fresh lettuce, great for salads.",
                ingredients: "Lettuce",
                nutritionalInfo: "Low in calories.",
                organic: true,
                slug: "lettuce",
                image: "https://example.com/lettuce.jpg",
              },
            ],
          },
          {
            id: "7ff490f9-4e93-4b14-b7de-e24c809e78c9",
            slug: "fresh-fruits",
            name: "Fresh Fruits",
            products: [
              {
                id: "6ed8737a-1288-476c-9a38-2a06c0bc1b1e",
                name: "Apples",
                quantity: "1kg",
                price: 150,
                description: "Crisp and juicy apples.",
                ingredients: "Apples",
                nutritionalInfo: "High in fiber.",
                organic: true,
                slug: "apples",
                image: "https://example.com/apples.jpg",
              },
              {
                id: "e397345d-5645-4c19-8fab-462f754c4d63",
                name: "Bananas",
                quantity: "1kg",
                price: 50,
                description: "Sweet bananas, great for snacks.",
                ingredients: "Bananas",
                nutritionalInfo: "Rich in potassium.",
                organic: false,
                slug: "bananas",
                image: "https://example.com/bananas.jpg",
              },
              {
                id: "f26effa8-ea88-4e6d-bb3e-b47f8bf7fe1b",
                name: "Grapes",
                quantity: "500g",
                price: 120,
                description: "Fresh grapes, sweet and juicy.",
                ingredients: "Grapes",
                nutritionalInfo: "Rich in antioxidants.",
                organic: true,
                slug: "grapes",
                image: "https://example.com/grapes.jpg",
              },
              {
                id: "07c02989-d1c7-48e4-ae46-9cc7254b5f86",
                name: "Oranges",
                quantity: "1kg",
                price: 80,
                description: "Juicy oranges, rich in vitamin C.",
                ingredients: "Oranges",
                nutritionalInfo: "High in vitamin C.",
                organic: false,
                slug: "oranges",
                image: "https://example.com/oranges.jpg",
              },
              {
                id: "2a569d5d-0d64-4e6d-9219-d62fe76d3eac",
                name: "Watermelons",
                quantity: "1kg",
                price: 60,
                description: "Refreshing watermelons, hydrating and sweet.",
                ingredients: "Watermelons",
                nutritionalInfo: "High in water content.",
                organic: false,
                slug: "watermelons",
                image: "https://example.com/watermelons.jpg",
              },
              {
                id: "c816aa06-fafd-43a9-9e85-4f95c313c078",
                name: "Cherries",
                quantity: "500g",
                price: 250,
                description: "Sweet cherries, perfect for desserts.",
                ingredients: "Cherries",
                nutritionalInfo: "Rich in antioxidants.",
                organic: true,
                slug: "cherries",
                image: "https://example.com/cherries.jpg",
              },
              {
                id: "d5e98d5b-782a-40d8-bf1d-f81702942ea1",
                name: "Peaches",
                quantity: "500g",
                price: 150,
                description: "Fresh peaches, juicy and sweet.",
                ingredients: "Peaches",
                nutritionalInfo: "High in vitamins A and C.",
                organic: false,
                slug: "peaches",
                image: "https://example.com/peaches.jpg",
              },
              {
                id: "79748172-6df7-4726-80ca-39dfd7e33f13",
                name: "Strawberries",
                quantity: "500g",
                price: 300,
                description: "Fresh strawberries, sweet and delicious.",
                ingredients: "Strawberries",
                nutritionalInfo: "High in vitamin C.",
                organic: true,
                slug: "strawberries",
                image: "https://example.com/strawberries.jpg",
              },
              {
                id: "06f8b2e8-47e1-4da4-992a-2e29e4bf50b3",
                name: "Mangoes",
                quantity: "1kg",
                price: 200,
                description: "Ripe mangoes, sweet and juicy.",
                ingredients: "Mangoes",
                nutritionalInfo: "Rich in vitamins A and C.",
                organic: false,
                slug: "mangoes",
                image: "https://example.com/mangoes.jpg",
              },
              {
                id: "cd556953-c061-4bd9-8864-865c0ba1461a",
                name: "Pineapples",
                quantity: "1kg",
                price: 150,
                description: "Fresh pineapples, sweet and tangy.",
                ingredients: "Pineapples",
                nutritionalInfo: "Rich in vitamins and minerals.",
                organic: true,
                slug: "pineapples",
                image: "https://example.com/pineapples.jpg",
              },
            ],
          },
          {
            id: "c5a3d76d-2b4f-4897-84af-f33842ffe4ce",
            slug: "dairy-and-eggs",
            name: "Dairy & Eggs",
            products: [
              {
                id: "97b0ec5f-4153-44b9-9469-5f3b8927fbf7",
                name: "Milk",
                quantity: "1L",
                price: 70,
                description: "Fresh cow's milk, rich in calcium.",
                ingredients: "Milk",
                nutritionalInfo: "Good source of protein.",
                organic: false,
                slug: "milk",
                image: "https://example.com/milk.jpg",
              },
              {
                id: "d9c89dee-91a5-4a79-8425-ac76f9d4b29a",
                name: "Eggs",
                quantity: "6pcs",
                price: 60,
                description: "Fresh chicken eggs.",
                ingredients: "Eggs",
                nutritionalInfo: "High in protein.",
                organic: true,
                slug: "eggs",
                image: "https://example.com/eggs.jpg",
              },
              {
                id: "0a26840c-f449-4713-8bb8-0564a5c255b9",
                name: "Butter",
                quantity: "200g",
                price: 120,
                description: "Creamy butter for cooking.",
                ingredients: "Cream",
                nutritionalInfo: "Rich in fat.",
                organic: false,
                slug: "butter",
                image: "https://example.com/butter.jpg",
              },
              {
                id: "7dff65cd-8fa7-4051-bd5d-c266e5a5b225",
                name: "Cheese",
                quantity: "200g",
                price: 200,
                description: "Tasty cheese, perfect for sandwiches.",
                ingredients: "Milk",
                nutritionalInfo: "Good source of calcium.",
                organic: true,
                slug: "cheese",
                image: "https://example.com/cheese.jpg",
              },
              {
                id: "b78630cd-2d5e-4287-bbf4-000d33040e64",
                name: "Yogurt",
                quantity: "500g",
                price: 80,
                description: "Creamy yogurt, great for digestion.",
                ingredients: "Milk",
                nutritionalInfo: "Contains probiotics.",
                organic: false,
                slug: "yogurt",
                image: "https://example.com/yogurt.jpg",
              },
              {
                id: "e633b870-881e-455c-b429-0f9555eb2950",
                name: "Cream",
                quantity: "250g",
                price: 150,
                description: "Fresh cream for desserts.",
                ingredients: "Cream",
                nutritionalInfo: "Rich in fat.",
                organic: true,
                slug: "cream",
                image: "https://example.com/cream.jpg",
              },
              {
                id: "f6ffbc0b-2c14-4502-a396-94d39d557178",
                name: "Sour Cream",
                quantity: "200g",
                price: 100,
                description: "Tangy sour cream for dips.",
                ingredients: "Cream, Lactic Acid",
                nutritionalInfo: "Used in cooking.",
                organic: false,
                slug: "sour-cream",
                image: "https://example.com/sour-cream.jpg",
              },
              {
                id: "b788c34c-8e21-41fc-8da7-a187583b51d4",
                name: "Condensed Milk",
                quantity: "400g",
                price: 120,
                description: "Sweetened condensed milk.",
                ingredients: "Milk, Sugar",
                nutritionalInfo: "Used in desserts.",
                organic: true,
                slug: "condensed-milk",
                image: "https://example.com/condensed-milk.jpg",
              },
              {
                id: "3f0e3b7d-015d-4a0d-846c-4e0195c23c76",
                name: "Eggnog",
                quantity: "1L",
                price: 250,
                description: "Rich and creamy eggnog.",
                ingredients: "Eggs, Milk",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "eggnog",
                image: "https://example.com/eggnog.jpg",
              },
              {
                id: "1c3f6efd-9d6f-49d8-847e-53216f2cd444",
                name: "Paneer",
                quantity: "200g",
                price: 150,
                description: "Fresh paneer, perfect for Indian dishes.",
                ingredients: "Milk",
                nutritionalInfo: "High in protein.",
                organic: true,
                slug: "paneer",
                image: "https://example.com/paneer.jpg",
              },
            ],
          },
          {
            id: "578d2028-6a93-457f-8234-7b5eb8d8f0d3",
            slug: "grains-and-pulses",
            name: "Grains & Pulses",
            products: [
              {
                id: "3672f5e8-3cbb-4593-be4f-c1f32db993bd",
                name: "Rice",
                quantity: "1kg",
                price: 60,
                description: "Long grain rice, ideal for cooking.",
                ingredients: "Rice",
                nutritionalInfo: "Rich in carbohydrates.",
                organic: true,
                slug: "rice",
                image: "https://example.com/rice.jpg",
              },
              {
                id: "80a239ef-378e-405c-8b02-0afa68b5143e",
                name: "Wheat Flour",
                quantity: "1kg",
                price: 50,
                description: "Fresh wheat flour for baking.",
                ingredients: "Wheat",
                nutritionalInfo: "Rich in fiber.",
                organic: false,
                slug: "wheat-flour",
                image: "https://example.com/wheat-flour.jpg",
              },
              {
                id: "0af6e143-c982-42b4-a5f0-9cc29d14fe6f",
                name: "Lentils",
                quantity: "500g",
                price: 100,
                description: "High-protein lentils.",
                ingredients: "Lentils",
                nutritionalInfo: "Rich in protein.",
                organic: true,
                slug: "lentils",
                image: "https://example.com/lentils.jpg",
              },
              {
                id: "ca5eb12a-8235-4427-9583-2a1241912e72",
                name: "Chickpeas",
                quantity: "500g",
                price: 70,
                description: "Nutritious chickpeas.",
                ingredients: "Chickpeas",
                nutritionalInfo: "High in fiber.",
                organic: false,
                slug: "chickpeas",
                image: "https://example.com/chickpeas.jpg",
              },
              {
                id: "6358c0c4-2af1-4715-877b-5fdbda6f5316",
                name: "Oats",
                quantity: "500g",
                price: 80,
                description: "Healthy oats for breakfast.",
                ingredients: "Oats",
                nutritionalInfo: "High in fiber.",
                organic: true,
                slug: "oats",
                image: "https://example.com/oats.jpg",
              },
              {
                id: "86763257-e550-4d36-8aa0-1a382371e737",
                name: "Barley",
                quantity: "500g",
                price: 90,
                description: "Nutritious barley grains.",
                ingredients: "Barley",
                nutritionalInfo: "Rich in fiber.",
                organic: false,
                slug: "barley",
                image: "https://example.com/barley.jpg",
              },
              {
                id: "402d9c22-b409-447d-b0a0-b3be383cf9ba",
                name: "Quinoa",
                quantity: "500g",
                price: 300,
                description: "High-protein quinoa.",
                ingredients: "Quinoa",
                nutritionalInfo: "Complete protein source.",
                organic: true,
                slug: "quinoa",
                image: "https://example.com/quinoa.jpg",
              },
              {
                id: "bf45c684-e724-46e3-bcec-10c482e8b057",
                name: "Millets",
                quantity: "500g",
                price: 90,
                description: "Nutritious millets.",
                ingredients: "Millets",
                nutritionalInfo: "High in fiber.",
                organic: false,
                slug: "millets",
                image: "https://example.com/millets.jpg",
              },
              {
                id: "ebfac619-48fa-47f3-aa88-4eadf3fcbca0",
                name: "Pulses Mix",
                quantity: "500g",
                price: 150,
                description: "Mixed pulses for variety.",
                ingredients: "Various Pulses",
                nutritionalInfo: "Rich in protein.",
                organic: true,
                slug: "pulses-mix",
                image: "https://example.com/pulses-mix.jpg",
              },
              {
                id: "c21836a1-cdf1-436c-8088-2bf0ca506c4a",
                name: "Semolina",
                quantity: "500g",
                price: 50,
                description: "Fine semolina for desserts.",
                ingredients: "Semolina",
                nutritionalInfo: "Rich in carbohydrates.",
                organic: false,
                slug: "semolina",
                image: "https://example.com/semolina.jpg",
              },
            ],
          },
          {
            id: "978855d2-1c70-4809-9606-397f253677a8",
            slug: "oils-and-condiments",
            name: "Oils & Condiments",
            products: [
              {
                id: "b636b920-2267-4fd8-bf7f-49278fde839f",
                name: "Olive Oil",
                quantity: "500ml",
                price: 400,
                description: "Extra virgin olive oil.",
                ingredients: "Olives",
                nutritionalInfo: "Rich in monounsaturated fats.",
                organic: true,
                slug: "olive-oil",
                image: "https://example.com/olive-oil.jpg",
              },
              {
                id: "027f0f95-b76b-41d2-a9ec-6bab8cdd11db",
                name: "Coconut Oil",
                quantity: "500ml",
                price: 300,
                description: "Pure coconut oil.",
                ingredients: "Coconuts",
                nutritionalInfo: "Rich in medium-chain triglycerides.",
                organic: true,
                slug: "coconut-oil",
                image: "https://example.com/coconut-oil.jpg",
              },
              {
                id: "959e4513-8103-4ed8-8cd4-0d61b2395e67",
                name: "Mustard Oil",
                quantity: "500ml",
                price: 150,
                description: "Pure mustard oil.",
                ingredients: "Mustard Seeds",
                nutritionalInfo: "Good for heart health.",
                organic: false,
                slug: "mustard-oil",
                image: "https://example.com/mustard-oil.jpg",
              },
              {
                id: "4b17f75c-d85d-4526-b3ff-cc3b78078beb",
                name: "Soy Sauce",
                quantity: "250ml",
                price: 100,
                description: "Savory soy sauce.",
                ingredients: "Soybeans, Wheat, Salt",
                nutritionalInfo: "Low in calories.",
                organic: false,
                slug: "soy-sauce",
                image: "https://example.com/soy-sauce.jpg",
              },
              {
                id: "7defd3e7-8759-4728-9709-2453154794af",
                name: "Vinegar",
                quantity: "500ml",
                price: 50,
                description: "White vinegar for cooking.",
                ingredients: "Fermented Alcohol",
                nutritionalInfo: "Low in calories.",
                organic: false,
                slug: "vinegar",
                image: "https://example.com/vinegar.jpg",
              },
              {
                id: "3da95c01-61c1-4c29-90d9-499b5b0d04c6",
                name: "Ketchup",
                quantity: "500g",
                price: 120,
                description: "Tomato ketchup.",
                ingredients: "Tomatoes, Sugar, Vinegar",
                nutritionalInfo: "High in sugar.",
                organic: true,
                slug: "ketchup",
                image: "https://example.com/ketchup.jpg",
              },
              {
                id: "8855abd9-a727-47ce-9d68-3f3e7f9b2fcf",
                name: "Mayonnaise",
                quantity: "500g",
                price: 180,
                description: "Creamy mayonnaise.",
                ingredients: "Eggs, Oil, Vinegar",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "mayonnaise",
                image: "https://example.com/mayonnaise.jpg",
              },
              {
                id: "33c3f027-d9da-48b9-a667-f772fef17cfd",
                name: "Chili Sauce",
                quantity: "200g",
                price: 100,
                description: "Spicy chili sauce.",
                ingredients: "Chili Peppers, Vinegar",
                nutritionalInfo: "Low in calories.",
                organic: true,
                slug: "chili-sauce",
                image: "https://example.com/chili-sauce.jpg",
              },
              {
                id: "dd7aa0d0-8359-40b4-b41e-050834322ea6",
                name: "Hot Sauce",
                quantity: "200g",
                price: 150,
                description: "Spicy hot sauce.",
                ingredients: "Chili Peppers, Vinegar",
                nutritionalInfo: "Low in calories.",
                organic: false,
                slug: "hot-sauce",
                image: "https://example.com/hot-sauce.jpg",
              },
              {
                id: "17d7bfb0-a2f8-4158-a61d-f1be84e65aec",
                name: "Barbecue Sauce",
                quantity: "300g",
                price: 180,
                description: "Sweet and tangy barbecue sauce.",
                ingredients: "Tomatoes, Sugar, Vinegar",
                nutritionalInfo: "High in sugar.",
                organic: true,
                slug: "barbecue-sauce",
                image: "https://example.com/barbecue-sauce.jpg",
              },
            ],
          },
        ],
      },
      {
        id: "e038e0ab-28fe-4b11-81aa-56ffbf600ee3",
        slug: "snacks-and-drinks",
        name: "Snacks & Drinks",
        subCategories: [
          {
            id: "5777cef3-5ba9-4ab9-951f-aea7a2ba2e27",
            slug: "chips",
            name: "Chips",
            products: [
              {
                id: "e94f6d17-6343-49bc-95cb-a992c6748b91",
                name: "Potato Chips",
                quantity: "200g",
                price: 50,
                description: "Crispy potato chips.",
                ingredients: "Potatoes, Oil, Salt",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "potato-chips",
                image: "https://example.com/potato-chips.jpg",
              },
              {
                id: "1b6679cd-ff01-4753-a890-707e72cbd474",
                name: "Tortilla Chips",
                quantity: "150g",
                price: 70,
                description: "Crispy tortilla chips.",
                ingredients: "Corn, Oil, Salt",
                nutritionalInfo: "Gluten-free.",
                organic: true,
                slug: "tortilla-chips",
                image: "https://example.com/tortilla-chips.jpg",
              },
              {
                id: "220b2a5d-f570-4514-a353-c7087e0f33af",
                name: "Cheese Puffs",
                quantity: "100g",
                price: 80,
                description: "Cheese flavored puffs.",
                ingredients: "Corn, Cheese, Oil",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "cheese-puffs",
                image: "https://example.com/cheese-puffs.jpg",
              },
              {
                id: "4250b320-c89e-436f-a583-980ce052f5d4",
                name: "Veggie Chips",
                quantity: "150g",
                price: 90,
                description: "Healthy veggie chips.",
                ingredients: "Vegetables, Oil, Salt",
                nutritionalInfo: "Low in calories.",
                organic: true,
                slug: "veggie-chips",
                image: "https://example.com/veggie-chips.jpg",
              },
              {
                id: "79c33c4f-6a28-443e-9a43-0bd3b0151259",
                name: "Sweet Potato Chips",
                quantity: "150g",
                price: 100,
                description: "Crispy sweet potato chips.",
                ingredients: "Sweet Potatoes, Oil, Salt",
                nutritionalInfo: "High in fiber.",
                organic: true,
                slug: "sweet-potato-chips",
                image: "https://example.com/sweet-potato-chips.jpg",
              },
              {
                id: "5fb79f13-56ab-48eb-9f80-9ab2b6decf54",
                name: "BBQ Chips",
                quantity: "200g",
                price: 70,
                description: "Tangy BBQ flavored chips.",
                ingredients: "Potatoes, BBQ Seasoning, Oil",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "bbq-chips",
                image: "https://example.com/bbq-chips.jpg",
              },
              {
                id: "bf29fd71-f28c-4a36-9388-148c251c6533",
                name: "Onion Rings",
                quantity: "150g",
                price: 80,
                description: "Crispy onion rings.",
                ingredients: "Onions, Oil, Salt",
                nutritionalInfo: "High in calories.",
                organic: false,
                slug: "onion-rings",
                image: "https://example.com/onion-rings.jpg",
              },
              {
                id: "07aa5027-5af4-43f4-a6c6-0777cc16fcf3",
                name: "Nachos",
                quantity: "200g",
                price: 90,
                description: "Crunchy nachos.",
                ingredients: "Corn, Oil, Salt",
                nutritionalInfo: "Gluten-free.",
                organic: true,
                slug: "nachos",
                image: "https://example.com/nachos.jpg",
              },
              {
                id: "75bbdae8-b912-4c16-a487-9e3f605fc993",
                name: "Puffed Rice",
                quantity: "200g",
                price: 60,
                description: "Light and crispy puffed rice.",
                ingredients: "Rice, Oil, Salt",
                nutritionalInfo: "Low in calories.",
                organic: false,
                slug: "puffed-rice",
                image: "https://example.com/puffed-rice.jpg",
              },
              {
                id: "c94ac2d6-d77b-4201-926d-2e966664b0dd",
                name: "Seaweed Snacks",
                quantity: "100g",
                price: 150,
                description: "Healthy seaweed snacks.",
                ingredients: "Seaweed, Oil, Salt",
                nutritionalInfo: "Rich in vitamins.",
                organic: true,
                slug: "seaweed-snacks",
                image: "https://example.com/seaweed-snacks.jpg",
              },
            ],
          },
          {
            id: "555585b6-fa99-4e37-b0c8-ea154f8c6ee4",
            slug: "beverages",
            name: "Beverages",
            products: [
              {
                id: "964e3cd9-65c1-4ef5-8fad-dcfb290cde12",
                name: "Coke",
                quantity: "500ml",
                price: 50,
                description: "Classic cola drink.",
                ingredients: "Carbonated Water, Sugar, Color",
                nutritionalInfo: "High in sugar.",
                organic: false,
                slug: "coke",
                image: "https://example.com/coke.jpg",
              },
              {
                id: "f5475ff6-eaf1-45b1-8eb0-70d714d0cb0a",
                name: "Sprite",
                quantity: "500ml",
                price: 50,
                description: "Lemon-lime flavored soda.",
                ingredients: "Carbonated Water, Sugar, Lemon-lime Flavor",
                nutritionalInfo: "High in sugar.",
                organic: false,
                slug: "sprite",
                image: "https://example.com/sprite.jpg",
              },
              {
                id: "1f5aa231-44ec-419d-b303-22fd7ef744d8",
                name: "Fanta",
                quantity: "500ml",
                price: 50,
                description: "Orange flavored soda.",
                ingredients: "Carbonated Water, Sugar, Orange Flavor",
                nutritionalInfo: "High in sugar.",
                organic: false,
                slug: "fanta",
                image: "https://example.com/fanta.jpg",
              },
              {
                id: "538f2462-87f1-4a88-9cc2-a732d70e1a2c",
                name: "Water",
                quantity: "1L",
                price: 20,
                description: "Bottled water.",
                ingredients: "Water",
                nutritionalInfo: "Zero calories.",
                organic: true,
                slug: "water",
                image: "https://example.com/water.jpg",
              },
              {
                id: "b33e65b9-65c2-4b84-acfc-e853f85be367",
                name: "Juice",
                quantity: "1L",
                price: 150,
                description: "Fresh fruit juice.",
                ingredients: "Fruits, Water, Sugar",
                nutritionalInfo: "High in vitamins.",
                organic: true,
                slug: "juice",
                image: "https://example.com/juice.jpg",
              },
              {
                id: "c5a3d845-16c3-40aa-950b-3e864f5ec20e",
                name: "Tea",
                quantity: "500ml",
                price: 60,
                description: "Brewed tea.",
                ingredients: "Tea Leaves, Water, Sugar",
                nutritionalInfo: "Low in calories.",
                organic: true,
                slug: "tea",
                image: "https://example.com/tea.jpg",
              },
              {
                id: "527daad7-5967-4603-b14d-451cb48f314d",
                name: "Coffee",
                quantity: "250g",
                price: 200,
                description: "Ground coffee.",
                ingredients: "Coffee Beans",
                nutritionalInfo: "Rich in caffeine.",
                organic: true,
                slug: "coffee",
                image: "https://example.com/coffee.jpg",
              },
              {
                id: "8efe039a-ef3f-49af-9914-467dcc7cd90b",
                name: "Energy Drink",
                quantity: "250ml",
                price: 100,
                description: "Caffeinated energy drink.",
                ingredients: "Carbonated Water, Caffeine, Sugar",
                nutritionalInfo: "High in caffeine and sugar.",
                organic: false,
                slug: "energy-drink",
                image: "https://example.com/energy-drink.jpg",
              },
              {
                id: "2ec8fb05-77c1-41b0-b5af-54c35269ae24",
                name: "Smoothie",
                quantity: "250ml",
                price: 120,
                description: "Fruit smoothie.",
                ingredients: "Fruits, Yogurt, Sugar",
                nutritionalInfo: "High in vitamins.",
                organic: true,
                slug: "smoothie",
                image: "https://example.com/smoothie.jpg",
              },
              {
                id: "f0dff1d8-d550-401b-b38b-f0c6778a2c10",
                name: "Sports Drink",
                quantity: "500ml",
                price: 80,
                description: "Hydrating sports drink.",
                ingredients: "Water, Electrolytes, Sugar",
                nutritionalInfo: "Contains electrolytes.",
                organic: false,
                slug: "sports-drink",
                image: "https://example.com/sports-drink.jpg",
              },
            ],
          },
        ],
      },
      {
        id: "822acf33-b16a-495f-bc9b-f5a430ea35ed",
        slug: "beauty-and-personal-care",
        name: "Beauty & Personal Care",
        subCategories: [
          {
            id: "ea1d362d-54b7-4d82-b182-ea146156fe4a",
            slug: "skin-care",
            name: "Skin Care",
            products: [
              {
                id: "f9cb1bca-ba44-494c-92e8-6ed338043d8a",
                name: "Moisturizer",
                quantity: "50ml",
                price: 500,
                description: "Hydrating moisturizer for skin.",
                ingredients: "Water, Glycerin, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "moisturizer",
                image: "https://example.com/moisturizer.jpg",
              },
              {
                id: "75ea7813-8abc-4f30-905c-6283b972e07a",
                name: "Sunscreen",
                quantity: "50ml",
                price: 600,
                description: "Protective sunscreen.",
                ingredients: "Zinc Oxide, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "sunscreen",
                image: "https://example.com/sunscreen.jpg",
              },
              {
                id: "021d43b4-c803-4118-bd03-c8605cf5abc5",
                name: "Face Wash",
                quantity: "100ml",
                price: 300,
                description: "Gentle face wash.",
                ingredients: "Water, Surfactants",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "face-wash",
                image: "https://example.com/face-wash.jpg",
              },
              {
                id: "7f204e87-d06a-4d91-b99d-36b4402e87f3",
                name: "Face Serum",
                quantity: "30ml",
                price: 800,
                description: "Nourishing face serum.",
                ingredients: "Hyaluronic Acid, Glycerin",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "face-serum",
                image: "https://example.com/face-serum.jpg",
              },
              {
                id: "31319425-32c2-4ccb-8c5f-dc0d3e350765",
                name: "Face Mask",
                quantity: "100ml",
                price: 400,
                description: "Hydrating face mask.",
                ingredients: "Clay, Water",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "face-mask",
                image: "https://example.com/face-mask.jpg",
              },
              {
                id: "56ab123c-8bd8-45b0-815f-c08381f69ba2",
                name: "Lip Balm",
                quantity: "15g",
                price: 200,
                description: "Nourishing lip balm.",
                ingredients: "Beeswax, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "lip-balm",
                image: "https://example.com/lip-balm.jpg",
              },
              {
                id: "bbb75e53-de87-428d-8095-5b3e033cc677",
                name: "Eye Cream",
                quantity: "15g",
                price: 350,
                description: "Hydrating eye cream.",
                ingredients: "Water, Oils",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "eye-cream",
                image: "https://example.com/eye-cream.jpg",
              },
              {
                id: "86eb41d1-1d82-4198-9d09-a17721b9997c",
                name: "Facial Scrub",
                quantity: "100g",
                price: 450,
                description: "Exfoliating facial scrub.",
                ingredients: "Sugar, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "facial-scrub",
                image: "https://example.com/facial-scrub.jpg",
              },
              {
                id: "f28d9c09-9164-4796-a164-69027d026aa3",
                name: "Body Lotion",
                quantity: "200ml",
                price: 600,
                description: "Moisturizing body lotion.",
                ingredients: "Water, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "body-lotion",
                image: "https://example.com/body-lotion.jpg",
              },
              {
                id: "6574a2cd-2508-4a6d-9159-bc325b5ab824",
                name: "Hand Cream",
                quantity: "50ml",
                price: 250,
                description: "Nourishing hand cream.",
                ingredients: "Water, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "hand-cream",
                image: "https://example.com/hand-cream.jpg",
              },
            ],
          },
          {
            id: "ef101034-3758-4185-8786-5d5dcf1c567e",
            slug: "hair-care",
            name: "Hair Care",
            products: [
              {
                id: "a1df26a5-b6c0-42b9-8e0f-b59ffa773473",
                name: "Shampoo",
                quantity: "200ml",
                price: 400,
                description: "Cleansing shampoo.",
                ingredients: "Water, Surfactants",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "shampoo",
                image: "https://example.com/shampoo.jpg",
              },
              {
                id: "8049a9e2-572d-482b-a7cc-4048578c3a33",
                name: "Conditioner",
                quantity: "200ml",
                price: 450,
                description: "Moisturizing conditioner.",
                ingredients: "Water, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "conditioner",
                image: "https://example.com/conditioner.jpg",
              },
              {
                id: "9886e940-b2cd-43b5-9f4b-3fedbaa55243",
                name: "Hair Oil",
                quantity: "100ml",
                price: 300,
                description: "Nourishing hair oil.",
                ingredients: "Oils, Fragrance",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "hair-oil",
                image: "https://example.com/hair-oil.jpg",
              },
              {
                id: "36d541ee-92fd-40bf-801a-767654385335",
                name: "Hair Mask",
                quantity: "150ml",
                price: 600,
                description: "Deep conditioning hair mask.",
                ingredients: "Oils, Proteins",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "hair-mask",
                image: "https://example.com/hair-mask.jpg",
              },
              {
                id: "754e64bd-b67a-4907-8c53-2239a7b5a965",
                name: "Hair Spray",
                quantity: "200ml",
                price: 350,
                description: "Styling hair spray.",
                ingredients: "Water, Fragrance",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "hair-spray",
                image: "https://example.com/hair-spray.jpg",
              },
              {
                id: "3b6eece4-c810-42a7-a7b9-cfd1277ecd43",
                name: "Dandruff Shampoo",
                quantity: "200ml",
                price: 500,
                description: "Shampoo for dandruff control.",
                ingredients: "Water, Surfactants",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "dandruff-shampoo",
                image: "https://example.com/dandruff-shampoo.jpg",
              },
              {
                id: "65185ea1-02a0-41a4-bf8a-1ed7576d5326",
                name: "Hair Gel",
                quantity: "150g",
                price: 250,
                description: "Styling hair gel.",
                ingredients: "Water, Gels",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "hair-gel",
                image: "https://example.com/hair-gel.jpg",
              },
              {
                id: "d82e3c9c-eab7-4998-9627-51b6b5bf96c0",
                name: "Heat Protectant",
                quantity: "150ml",
                price: 400,
                description: "Protects hair from heat damage.",
                ingredients: "Water, Oils",
                nutritionalInfo: "N/A",
                organic: true,
                slug: "heat-protectant",
                image: "https://example.com/heat-protectant.jpg",
              },
              {
                id: "67d4bd61-8527-4282-b09f-0ed942c0c1b7",
                name: "Hair Detangler",
                quantity: "200ml",
                price: 350,
                description: "Detangles hair easily.",
                ingredients: "Water, Surfactants",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "hair-detangler",
                image: "https://example.com/hair-detangler.jpg",
              },
              {
                id: "3c47e707-3071-40ba-8b6f-9e03fd1ba78c",
                name: "Hair Color",
                quantity: "100ml",
                price: 800,
                description: "Permanent hair color.",
                ingredients: "Dyes, Chemicals",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "hair-color",
                image: "https://example.com/hair-color.jpg",
              },
            ],
          },
        ],
      },
      {
        id: "c361fa4b-a2cf-4e31-a8f6-2d7a088d6c3d",
        slug: "household-essentials",
        name: "Household Essentials",
        subCategories: [
          {
            id: "f64aada5-76ac-49fb-a8ac-06fdfaed824c",
            slug: "cleaning-supplies",
            name: "Cleaning Supplies",
            products: [
              {
                id: "244b71d7-06a2-4897-b6e8-929eaf0e3fa3",
                name: "All-purpose Cleaner",
                quantity: "500ml",
                price: 250,
                description: "Effective all-purpose cleaner.",
                ingredients: "Surfactants, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "all-purpose-cleaner",
                image: "https://example.com/all-purpose-cleaner.jpg",
              },
              {
                id: "bcaaa91f-15fa-4641-bd5c-507dab8601b7",
                name: "Dish Soap",
                quantity: "500ml",
                price: 150,
                description: "Dishwashing liquid.",
                ingredients: "Surfactants, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "dish-soap",
                image: "https://example.com/dish-soap.jpg",
              },
              {
                id: "fea7eecb-a09c-43ca-8a34-cce938e9de4a",
                name: "Laundry Detergent",
                quantity: "1L",
                price: 300,
                description: "Laundry detergent for machines.",
                ingredients: "Surfactants, Fragrance",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "laundry-detergent",
                image: "https://example.com/laundry-detergent.jpg",
              },
              {
                id: "aff0c261-33c9-401d-924f-26df3f884a42",
                name: "Glass Cleaner",
                quantity: "500ml",
                price: 200,
                description: "Cleans glass surfaces.",
                ingredients: "Surfactants, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "glass-cleaner",
                image: "https://example.com/glass-cleaner.jpg",
              },
              {
                id: "1731961b-067a-4374-84a7-15f2576505a6",
                name: "Toilet Cleaner",
                quantity: "500ml",
                price: 250,
                description: "Cleans and disinfects toilets.",
                ingredients: "Surfactants, Acids",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "toilet-cleaner",
                image: "https://example.com/toilet-cleaner.jpg",
              },
              {
                id: "d8f9798a-9271-4a30-baf8-eb1a8ac5fa85",
                name: "Fabric Softener",
                quantity: "1L",
                price: 350,
                description: "Makes laundry soft and fresh.",
                ingredients: "Surfactants, Fragrance",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "fabric-softener",
                image: "https://example.com/fabric-softener.jpg",
              },
              {
                id: "22028e57-be59-476f-b494-8202ac321460",
                name: "Floor Cleaner",
                quantity: "1L",
                price: 300,
                description: "Cleans floors effectively.",
                ingredients: "Surfactants, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "floor-cleaner",
                image: "https://example.com/floor-cleaner.jpg",
              },
              {
                id: "8f5e04d9-49df-4ceb-be32-54d885a7e0fb",
                name: "Oven Cleaner",
                quantity: "500ml",
                price: 400,
                description: "Cleans ovens and grills.",
                ingredients: "Surfactants, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "oven-cleaner",
                image: "https://example.com/oven-cleaner.jpg",
              },
              {
                id: "52674502-f45f-466a-939a-5a7ff7e46e44",
                name: "Air Freshener",
                quantity: "300ml",
                price: 250,
                description: "Freshens the air.",
                ingredients: "Fragrance, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "air-freshener",
                image: "https://example.com/air-freshener.jpg",
              },
              {
                id: "6b847f7a-2707-4527-a8f2-b2ac7ca8e92c",
                name: "Bleach",
                quantity: "1L",
                price: 150,
                description: "Disinfectant bleach.",
                ingredients: "Sodium Hypochlorite, Water",
                nutritionalInfo: "N/A",
                organic: false,
                slug: "bleach",
                image: "https://example.com/bleach.jpg",
              },
            ],
          },
        ],
      },
    ],
  },
];
